spring:
    datasource:
        #driverClassName: org.h2.Driver
        #username: sa
        #password: password
        #url: jdbc:h2:mem:testdb  #memory
        #driverClassName: org.h2.Driver
        url: ${JDBC_DATABASE_URL} #jdbc:postgresql://ec2-3-217-68-126.compute-1.amazonaws.com:5432/d3rqnamkvbmsas
        username: ${JDBC_DATABASE_USERNAME} #btuowaqhddgndo
        password: ${JDBC_DATABASE_PASSWORD} #80eeb4f2a12f7fa01cdbf23b6b9fa6dbdf7a885f1966e2ad8fc85ef247e9ef4d
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Hibernate ddl auto (create, create-drop, validate, update)
    application:
        name:   mySringBoot
    error:
        whitelabel:
            enabled: false
    data:
        mongodb:
            uri: mongodb+srv://thaijavadev:smZUAbCejaPfnKx5@cluster0.rdast.mongodb.net/test
            database: test
server:
    port: ${PORT:5000}